# Generated by Django 2.1.4 on 2019-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_title', models.CharField(max_length=200)),
                ('hand_content', models.TextField()),
                ('hand_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
