# Generated by Django 2.1.4 on 2019-05-14 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_situation', models.CharField(max_length=200)),
                ('situation_summary', models.CharField(max_length=200)),
                ('situation_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Situations',
            },
        ),
        migrations.AddField(
            model_name='hand',
            name='hand_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='hand',
            name='hand_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='hand',
            name='hand_situation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.HandSituation', verbose_name='Situation'),
        ),
    ]
